server:
  port: 8081

spring:
  application:
    name: "ms-technology"
  devtools:
    add-properties: false

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    schema: ${R2DBC_SCHEMA}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

springdoc:
  swagger-ui:
    path: "/technology/api/doc/swagger-ui.html"
  api-docs:
    path: "/technology/api/doc/api-docs"

routes:
  paths:
    technologies: "/technology/api/v1/technologies"
